spring:
  config:
    import: "optional:configserver:"
  application:
    name: gateway-service
cloud:
  config:
    discovery:
      service:Id: config-service
      enabled: true
    gateway:
      routes:
        - id: checkout-service
          uri: http://localhost:8082
          predicates:
            - Path=/checkout

server:
  port: 8084