spring:
  config:
    import: "optional:configserver:"
    enable: false
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        serviceId: config-service
        enabled: true
    gateway:
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout/**


server:
 port: 8084