version: '2.1'

services:
  checkout-service:
    build: checkout-service/
    mem_limit: 512m
    ports:
      - 8081:8080
  payments-service:
    build: payments-service/
    mem_limit: 512m
    ports:
      - 8082:8080
  eureka-server:
    build: eureka-server/
    mem_limit: 512m
    ports:
      - 8761:8761
  config-server:
    build: config-server/
    mem_limit: 512m
    ports:
      - 8889:8889
  gateway:
    build: gateway/
    mem_limit: 512m
    ports:
      - 8085:8085
  notifications-service:
    build: notifications/
    mem_limit: 512m
    ports:
      - 8083:8080
  products-service:
    build: products/
    mem_limit: 512m
    ports:
      - 8084:8080